/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `person`;

CREATE TABLE `person` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_age` SMALLINT UNSIGNED NOT NULL DEFAULT 20,
  `name` TEXT NOT NULL,
  `update` TIMESTAMP NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `name_i`
  ON `person` (`name`);

CREATE INDEX `update_i`
  ON `person` (`update`);

